-
  version: 0.0.{build}
  configuration: Release
  image: Visual Studio 2019
  services: mssql2017
  install:
  - ps: ./versionize.ps1 | %{ Update-AppveyorBuild -Version $_ }

  build_script:
  - dotnet build -p:Version=%APPVEYOR_BUILD_VERSION%
  after_build:
  - cmd: >-
      dotnet test --no-build

      dotnet pack src/HybridDb/ -c Release --include-symbols -p:SymbolPackageFormat=snupkg -p:Version=%APPVEYOR_BUILD_VERSION%
      
      dotnet pack src/HybridDb.NewtonsoftJson/ -c Release -p:Version=%APPVEYOR_BUILD_VERSION%
      
  artifacts:
  - path: '*/**/*.nupkg'
  deploy:
  - provider: NuGet
    on:
      APPVEYOR_REPO_TAG: true
    api_key:
      secure: mxoXEn4ViOiSmiDLbqcyGpZsm93dWpqug3c+/H6Ra7w2WOCpsTLjAJSpapHheUkh
  - provider: GitHub
      release: HybridDb $(APPVEYOR_BUILD_VERSION)
      description: 'Release description'
      auth_token:
        secure: <your encrypted token> # your encrypted token from GitHub
      artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
      draft: false
      prerelease: false
      on:
        branch: master                 # release from master branch only
        APPVEYOR_REPO_TAG: true        # deploy on tag push only      