-
  branches:
    only:
      - master
      - appveyor-setup
  version: 3.0.{build}
  configuration: Release
  image: Visual Studio 2019
  services: mssql2017
  build_script:
  - dotnet build -p:Version=%APPVEYOR_BUILD_VERSION%
  after_build:
  - cmd: >-
      dotnet test --no-build

      dotnet pack src/HybridDb/ -c Release --include-symbols -p:SymbolPackageFormat=snupkg -p:Version=%APPVEYOR_BUILD_VERSION%
      
      dotnet pack src/HybridDb.NewtonsoftJson/ -c Release -p:Version=%APPVEYOR_BUILD_VERSION%
      
  artifacts:
  - path: '*/**/*.nupkg'
  deploy:
  - provider: NuGet
    api_key:
      secure: brp5M3jywSDGAUNFwPkKnY+chbECojhp8T5rHASXQUEBIw+Uc8Q5dlkX6Cr62T53