-
  branches:
    only:
      - master
  version: 2.0.{build}-alpha
  configuration: Release
  platform: Any CPU
  image: Visual Studio 2019
  services: mssql2014
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  build:
    project: HybridDb.sln
    verbosity: minimal
  after_build:
  - cmd: >-
      dotnet pack src\HybridDb\HybridDb.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
      dotnet pack src\HybridDb.NewtonsoftJson\HybridDb.NewtonsoftJson.csproj -Version %APPVEYOR_BUILD_VERSION%
  artifacts:
  - path: '*/**/*.nupkg'
  deploy:
  - provider: NuGet
    api_key:
      secure: rTAOxhsBekNlEb9IN6Iyy5mayYbiTTIWidYKB4f1ZyRbwiIeqjFr0x6qDZQM6RYP