-
  branches:
    only:
      - master
      - appveyor-setup
  version: 0.0.{build}
  configuration: Release
  image: Visual Studio 2019
  services: mssql2017
  init:
  - ps: versionize.ps1

  build_script:
  - dotnet build -p:Version=%APPVEYOR_BUILD_VERSION%
  after_build:
  - cmd: >-
      dotnet test --no-build

      dotnet pack src/HybridDb/ -c Release --include-symbols -p:SymbolPackageFormat=snupkg -p:Version=%APPVEYOR_BUILD_VERSION%
      
      dotnet pack src/HybridDb.NewtonsoftJson/ -c Release -p:Version=%APPVEYOR_BUILD_VERSION%
      
  artifacts:
  - path: '*/**/*.nupkg'
  deploy:
  - provider: NuGet
    on:
      APPVEYOR_REPO_TAG: true
    api_key:
      secure: mxoXEn4ViOiSmiDLbqcyGpZsm93dWpqug3c+/H6Ra7w2WOCpsTLjAJSpapHheUkh