-
  version: 0.0.{build}
  configuration: Release
  image: Visual Studio 2019
  services: mssql2017
  install:
  - ps: >-
      $ErrorActionPreference = "Stop";

      ./versionize.ps1 | %{ Update-AppveyorBuild -Version $_ };

      # Environment variables are truncated to the first line in appveyor (see https://github.com/appveyor/ci/issues/1688) 
      # so we join these together as html - and it finally works. We take the message from the tag and use as release message.
      $env:REPO_TAG_DESCRIPTION=(git tag -l --format='%(contents)' $env:APPVEYOR_REPO_TAG_NAME | Where-Object {$_}) -join "<br />";

      Write-Host $env:REPO_TAG_DESCRIPTION;

  build_script:
  - dotnet build -p:Version=%APPVEYOR_BUILD_VERSION%
  after_build:
  - cmd: >-
      dotnet test --no-build

      dotnet pack src/HybridDb/ -c Release --include-symbols -p:SymbolPackageFormat=snupkg -p:Version=%APPVEYOR_BUILD_VERSION%
      
      dotnet pack src/HybridDb.NewtonsoftJson/ -c Release -p:Version=%APPVEYOR_BUILD_VERSION%
      
  artifacts:
  - path: '*/**/*.nupkg'
  deploy:
  - provider: NuGet
    on:
      APPVEYOR_REPO_TAG: true
    api_key:
      secure: mxoXEn4ViOiSmiDLbqcyGpZsm93dWpqug3c+/H6Ra7w2WOCpsTLjAJSpapHheUkh
  - provider: GitHub
    release: $(APPVEYOR_BUILD_VERSION)
    tag: $(APPVEYOR_REPO_TAG_NAME)   # need to apply the tag it self again, or else github will add one and restart the build recursively
    description: $(REPO_TAG_DESCRIPTION)
    auth_token:
      secure: nLfUisFRoNH5oToYu1cos52aKjQzO8jPVEdID9FoaKLSPaIJsfXK3Bb43MeHi/eQ
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      # branch: master    # right now we can't restrict the release to master only as tags are counted as branches too. We'll delete the prereleases manually.
      APPVEYOR_REPO_TAG: true