version: 0.0.{build}
configuration: Release
image: Visual Studio 2019
skip_branch_with_pr: true
environment:
  NUGET_API_KEY:
    secure: mxoXEn4ViOiSmiDLbqcyGpZsm93dWpqug3c+/H6Ra7w2WOCpsTLjAJSpapHheUkh
init:
- net start MSSQL$SQL2019
# Environment variables are truncated to the first line in appveyor (see https://github.com/appveyor/ci/issues/1688) 
# so we join these together as html - and it finally works. We take the message from the tag and use as release message.
# Also comments in powershell scripts does not work: https://help.appveyor.com/discussions/problems/32779-powershell-comments-changes-the-script
install:
- ps: >-
    $ErrorActionPreference = "Stop";

    $env:BRANCH_NAME = ($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH, $env:APPVEYOR_REPO_BRANCH -ne $null)[0];

    ./versionize.ps1 $env:BRANCH_NAME $env:APPVEYOR_BUILD_NUMBER | %{ Update-AppveyorBuild -Version $_ };

    $env:REPO_TAG_DESCRIPTION = (git tag -l --format='%(contents)' $env:APPVEYOR_REPO_TAG_NAME | Where-Object {$_}) -join "<br />";

build_script:
- ps: >-
    ./build.ps1 $env:APPVEYOR_BUILD_VERSION $env:NUGET_API_KEY
artifacts:
- path: '*/**/*.nupkg'
deploy:
#- provider: NuGet
#  name: Official Nuget
#  on:
#    APPVEYOR_REPO_TAG: true
#  api_key:
#    secure: mxoXEn4ViOiSmiDLbqcyGpZsm93dWpqug3c+/H6Ra7w2WOCpsTLjAJSpapHheUkh
- provider: NuGet
  name: Github Nuget
  server: https://nuget.pkg.github.com/asgerhallas/index.json
  username: asgerhallas
  api_key:
      secure: AkvDrkmH7Rioub/XKuzoRza1/F/VDkw59noaQPHw8UF2+NI0JIyR5QsU86O73n+L
  #- provider: GitHub
  #  name: Github Releases
  #  release: $(APPVEYOR_BUILD_VERSION)
  #  tag: $(APPVEYOR_REPO_TAG_NAME)   # need to apply the tag it self again, or else github will add one and restart the build recursively
  #  description: $(REPO_TAG_DESCRIPTION)
  #  auth_token:
  #    secure: AkvDrkmH7Rioub/XKuzoRza1/F/VDkw59noaQPHw8UF2+NI0JIyR5QsU86O73n+L
  #  artifact: /.*\.nupkg/
  #  draft: false
  #  prerelease: false
  #  on:
  #    # branch: master    # right now we can't restrict the release to master only as tags are counted as branches too. We'll delete the prereleases manually.
  #    APPVEYOR_REPO_TAG: true