# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "github-actions-5" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      shell: pwsh
      run: ./build.ps1 1.0.0
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: /**/*.nupkg
